### ISSUE TITLE
Testing Suite Setup for Core flows

### ISSUE THREAD

**Issue by tushar5526** [Mission-Prerna/nl-apis#100]
Context: https://github.com/Mission-Prerna/nl-apis/pull/99

I have added a unit test that works, but we can't move it to GHA yet. I would need to invest more time in this to fix:

Use test containers for each test run.
Reduce the seed data script so that it can be loaded quickly into test containers.
Jest tests currently don't terminate and hang after running successfully with an error saying
Jest did not exit one second after the test run was completed.

```
This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

which will need some time to investigate.

**Comment by nikhil241** [comment]
@karntrehan and @dhruv-1001 
1. **Write Comprehensive Tests:** Use Jest to focus on unit tests for key components.
2. **Set Up GitHub Actions for CI:** Automate testing and code coverage reporting with GitHub Actions.
3. **Integrate Codecov:** Upload and monitor coverage data using Codecov.
4. **Add Badges to README** Display build status and coverage badges.

**Comment by karntrehan** [comment]
Detailed analysis on: 

- Framework
- Type of test
- Automated running of test
- Success metric - Coverage tools.

**Comment by AakashSatpute119** [comment]
- Review existing test cases by @nikhil241 
- Focus on unit test cases.
- complete 40% test cases by end of this week.

**Comment by karntrehan** [comment]
Doc link: https://docs.google.com/document/d/1o5UlgHorjGCNRLB3Kus1IWV7CqT5N3Dfafy6EY3w1T0/edit?usp=sharing

**Comment by dhruv-1001** [comment]
@nikhil241 to raise a PR today.

**Comment by nikhil241** [comment]
> @nikhil241 to raise a PR today.

PR is raised.

Here's the coverage screenshot of Jest

![image](https://github.com/user-attachments/assets/71c9271f-6830-49fc-be1f-ef7c5704a38d)

**Comment by nikhil241** [comment]
> > @nikhil241 to raise a PR today.
> 
> PR is raised for data-services [NipunSahAIyak/data-service#55](https://github.com/NipunSahAIyak/data-service/pull/55) .
> 
> Here's the coverage screenshot of Jest
> 
> ![image](https://private-user-images.githubusercontent.com/11809438/352907734-71c9271f-6830-49fc-be1f-ef7c5704a38d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDEwMTIsIm5iZiI6MTcyMjQwMDcxMiwicGF0aCI6Ii8xMTgwOTQzOC8zNTI5MDc3MzQtNzFjOTI3MWYtNjgzMC00OWZjLWJlMWYtZWY3YzU3MDRhMzhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDA0MzgzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyMGJkOTg4ZDM3MTVkMjBiMjU2MjJjYTNhMGU5ZGRjODk2ODBiYmM2ODA0ZjA3MTY4OTFlYTM4NzIxZDZmMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gjUCaEcKRdcanek6HJVxZFFQpsor4Sz-tr9IbGZ9MC8)

This is related to the data-service, so I moved this conversation to the NISAI project for tracking.

**Comment by karntrehan** [comment]
To be closed today.
