### ISSUE TITLE
Remove SQL Injection from NL-APIs

### ISSUE THREAD

**Issue by tushar5526** [Mission-Prerna/nl-apis#111]
Moving this ticket from the master ticket out to track separately. 

Related PR https://github.com/Mission-Prerna/nl-apis/pull/110

**Comment by tushar5526** [comment]
All flows need to be tested, @aakashyadav-kgp please test this whenever you test the whole app e2e.

**Comment by rohitsamagra** [comment]
- @AakashSatpute119  tested and working well
