### ISSUE TITLE
[BE] API for creation of ODK Forms

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#126]
With the selection of odk sets for creation of ODK forms to support large quantity of sets, we need to design an API to convert questions and choices to ODK forms. 

Assumptions: 
* Questions and choices are shared as a csv. Questions are mapped to a competency. Correct choice is marked clearly.
* Output ODKs would be uploaded to central separately. 

Acceptance criteria: 
* ~Pick all questions & choices of a competency.~ Pick questions of a group / set and competencies 
* Create groups of set with each group containing max 100 sets.
* Convert questions to an ODK of this format: https://drive.google.com/open?id=1YthkyJLBAb4UNm_J-dwTpeZuSzCo0jyF&usp=drive_copy
    * Corresponding excel: https://docs.google.com/spreadsheets/d/1b-OEINT7LCQ4j8FNGw0PZ7m-PM0N1B26C99udUVc70U/edit?usp=sharing.
* Replace values in the tags directly.
* The output XML is valid and works on ODK Central.

**Comment by rohitsamagra** [comment]
- Plan for implementation in 2403
- Execution in 2404

**Comment by rohitsamagra** [comment]
- @tushar5526 to update approaches with pro/con analysis

**Comment by tushar5526** [comment]
Approach 1
-------------
Replace the form values in the XML template directly from the given JSON. 

Pros:
1. A smaller number of steps to create the final XML, which helps in debugging. 
2. Straight forward approach to replace the values in XML template. 

Cons:
1. The number of questions sets in a group is not completely dynamic. It will depend on the XML template being used. 
2. XML is comparatively difficult to debug compared to Excel sheets currently in use to create files. 

Approach 2
------------
Convert the JSON to an Excel file and then use https://github.com/XLSForm/pyxform to convert it into an ODK XML file. 

Pros. 
1. The number of question sets in a group, number of questions in a set etc. can be made dynamic. 
2. Easier to check the correctness of conversion of JSON to Excel as compared to JSON to XML.  
3. Create an Excel first which can be used to create some minor tweaks. For example - the input data will likely have some human errors - we might find them later and want to fix them in the form. PT would be able to do it. 
4. Manual form creation remains the same way. 
Cons. 
1. 2-step process as compared to the above approach
2. Dependency on the correct functionality of a 3rd part package. Bugs present in the 3rd party package might generate faulty XML files which will make debugging difficult.

**Comment by rohitsamagra** [comment]
- To finalize the approach

**Comment by tushar5526** [comment]
Action Items

- [ ] Check ODK API to upload Excel directly.
- [ ] Akash to check for calculation logic in dynamic question sets.

**Comment by charanpreet-s** [comment]
@AakashSatpute119 to have final discussion with @karntrehan to finalize the approach

**Comment by karntrehan** [comment]
Planning closed. We are going with approach 2. Development to be tracked in #129
