### ISSUE TITLE
[BE] Generator Block [V1]

### ISSUE THREAD

**Issue by tushar5526** [Mission-Prerna/nl-apis#141]
Generator User flow. 

1. User logs into generator admin block. 
2. [Competency CRUD Screen] User creates competencies using the admin panel. 
3. [Segment CRUD Screen] User creates segment on the admin Panel. 
4. [Generator Screen] User then selects the competency and generates questions by giving prompts to autotune.
5. [Generator Screen] User selects the ODK central instance and the ODK central project to ingest forms into. (Get clarity on how many central. instances and project do we support - currently it seems we will have 1 instance and 1 project - so this step can be skipped)
6.[Generator Screen] User select the question group to which the new generated questions are supposed to be added (default is to create new group). The user hits the ingest button and data is ingested. Successful forms are returned. 
7. [Segment Mapping screen] User manually maps segments to question groups.

**Comment by rohitsamagra** [comment]
@rohitsamagra and @UtsavThapliyal to discuss

**Comment by charanpreet-s** [comment]
To be closed by Friday

**Comment by charanpreet-s** [comment]
@tushar5526 to discuss with @karntrehan

**Comment by tushar5526** [comment]
Discussed with Karan. 

The generator block will use Core-service to help generate competencies and executors configs. Updated flow is as follows. 

1. User logs into generator admin block. 
2. [Competency CRUD Screen] User creates competencies using the admin panel. 
3. [Segment CRUD Screen] User creates segment on the admin Panel. 
4. [Executor CRUD Screen] User creates executors. 
5. [Generator Screen] User then selects the competency, the executor to be used and generates questions by giving prompts to autotune. It then hits "ingest" to start ingestion of forms. The returned response contains the new mappings. 
7. [Segment Mapping screen] User manually maps segments to question groups received in the response above.

**Comment by tushar5526** [comment]
Design and discussion to be picked next sprint.
