### ISSUE TITLE
[Parent Ticket] Discussion on NISAI

### ISSUE THREAD

**Issue by tushar5526** [Mission-Prerna/nl-apis#172]
Parent ticket to track all the threads. 

- [x] #173
- [x] #174
- [x] #175
- [x] Figure out releases and feature backlog - Releases with Demos
- [ ] Devops needs for single instance - Infra needs

Questions from BhasAI:

- [x] Autotune placement?
- [x] UserService placement?
- [x] Communication layer?
- [x] Telemetry service placement? - Bhasai Mesh: Observability
- [x] BSTT Service placement? - Accuracy & Availability - Dynamic model & provider selection : Layer?

------

- [x] How do we handle already created typeform / other player forms? - Transformer before ingestion, Generator for Typeform, Break transformer into transform & Mapper. 
- [x] Discuss partnership with MSDF with leadership to unify education flows with Nisai

**Comment by rohitsamagra** [comment]
- Autotune, BSTT Service placement, User Service Placement discussion level is clear
