### ISSUE TITLE
NISAI multi-tenant architecture design and refactoring of current architecture

### ISSUE THREAD

**Issue by tushar5526** [Mission-Prerna/nl-apis#174]
- [x] Global questionnaires, competencies and executors - registries
- [x] Tenant specific competencies, questionnaires and executors.
- [x] Define where stateful data would reside and configured - On Nisai, On State, On State + Nisai
- [x] Data - Master data, Transaction & History, Competency & Questionnaire.
- [x] Authentication for admins and end users across admin and executors.

**Comment by AakashSatpute119** [comment]
Anylsis done and signed of by leadership.
