### ISSUE TITLE
[Automation] Testing NL APIs

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#18]
We need to test the NL APIs. 

- [x] Select framework for testing
- [ ] Write tests
- [ ] Automate tests to run for every push.

**Comment by choxx** [comment]
@Nirali010129 @karntrehan here is the link to Postman collection: https://api.postman.com/collections/4552036-bb891a4e-da4a-42a2-a984-9e68e4fd36c8?access_key=PMAT-01H407FXBN1R3QXZJAMJTTSRBN

**Comment by choxx** [comment]
Postman sent a warning alert for attaching postman collection link above. Removing the collection link from ticket. Please ping to get new (rotated) collection link.

![Image](https://github.com/Mission-Prerna/nl-apis/assets/11666456/f0206aff-4664-4de0-a8ed-87ec0aa997a9)

**Comment by choxx** [comment]
@Nirali010129 API documentation has been added in the Postman collection itself for success criteria.

**Comment by charanpreet-samagra** [comment]
@Nirali010129 to present demo for the findings

**Comment by aakashyadav-kgp** [comment]
Need to finalise the tool for automation testing. Discussing between postman and burp suite.

**Comment by karntrehan** [comment]
Postman is better compared to soapUI. To check on sharing of scripts across users.

**Comment by choxx** [comment]
Still looking for Postman alternatives. We tried looking at Hoppscotch.io, which doesn't feel the right fit.

**Comment by karntrehan** [comment]
Demo undertaken yesterday. Postman is the right framework to use. Tests written for some rest APIs. Tests to be written for GraphQL APIs. Plan is to combine API definitions, documentation and tests into a single collection and share across the team. 

@Nirali010129 and @AakashSatpute119 to continue on this.

**Comment by Nirali010129** [comment]
1. Send OTP 
2. Verify OTP
3. Set mentor pin
4. Login
5. Create assessment survey result
6. Create assessment visit result
7. List mentor school
8. Home Overview
9. metadata
10. mentor detail

1. [ ]

**Comment by karntrehan** [comment]
Almost done. To be finished today. Collection to be shared here.

**Comment by Nirali010129** [comment]
https://drive.google.com/file/d/1wOxbSz3o1Rw7fVDsWPQcfZiUIAyQxdLt/view?usp=sharing

please Review @choxx @AakashSatpute119 

cc: @karntrehan

**Comment by karntrehan** [comment]
Teacher flow to be added as an enhancement.

**Comment by Nirali010129** [comment]
[Uploading NL APIs Teacher Flow.postman_collection.docx…]()

**Comment by Nirali010129** [comment]
https://docs.google.com/document/d/1b-bfqBo1-TZdYR3yBpelaqUxvZI7cuXd/edit?usp=sharing&ouid=109508362438139603905&rtpof=true&sd=true
