### ISSUE TITLE
Bhashini Model Enhancements

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#182]
-  Accuracy to checked using Fuzzy Search + Bhashini Approach
-- Gautam is checking the script for how it is working on the children, difference between actual Bhashini and Steno result. Do we need the training or not?
- If not accurate after fuzzy search, train the model - do we have the data in the format required?
-- Gautam's sheet 
-- Aiming for 90-95%

**Comment by rohitsamagra** [comment]
- 89% with only Bhashini Model
- 95% with fuzzy
- Training might not be required
- Gautam to share in a well required format

**Comment by charanpreet-s** [comment]
@charanpreet-s to send mail with final results
