### ISSUE TITLE
[Examiner Flow]: Changes in Final Screen

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#186]
Changing the Summary Screen: 

- Showing NIPUN Status at every Grade Level
- In drop down, see the list of students
- Text with details of calculation

Figma Link: https://www.figma.com/file/KEv3Bga4hygJiw4QPFMxx3/NL-App_May_2023?type=design&node-id=856-584&mode=design&t=H3EKdz00eOH7Fcz2-0

- Old screen on the left changes to the new screen on the right

![Image](https://github.com/Mission-Prerna/nl-apis/assets/145356240/12e8938f-445b-49e8-8d12-40ac90a54204)

**Comment by karntrehan** [comment]
How is a class nipun? Whats the calculation for it?

**Comment by karntrehan** [comment]
Build: https://drive.google.com/open?id=1FdezjFSlcqTl8Q8UdzOAj44wAKpboXTY&usp=drive_copy
