### ISSUE TITLE
[RCT Implementation]: Remove Parent Flow from NL App

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#205]
- Disabling parent flow from the NL app for RCT implementation

**Comment by rohitsamagra** [comment]
- Harsh to pick up once free

**Comment by AakashSatpute119** [comment]
Bugs : 

- [ ] 1. In examiner flow Geo fencing is not working https://screenpal.com/watch/cZhilrVMLfH

**Comment by rohitsamagra** [comment]
@charanpreet-s to check the chat bot bug and examiner to be checked by Harsh
