### ISSUE TITLE
[RCT Implementation]: Disabling NL App for Group A schools during RCT implementation (~800 schools)

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#206]
**Goal:** 

**Acceptance Criteria:** 

**Telemetry Information:** 

**Test Cases:** 

- List of schools (ask for them)
- Teacher flow will be removed
- Mentor flow will be there
- Examiner flow - Snehi to get back

To picked after June 10th when list of schools are shared

**Comment by charanpreet-s** [comment]
@VargishChauhan to connect with PT for this

**Comment by karntrehan** [comment]
Blocked on PT.

**Comment by AakashSatpute119** [comment]
Data from PT to come today.

**Comment by VargishChauhan** [comment]
@charanpreet-s   PT has provided the list of the schools . You can refer the below sheet

https://docs.google.com/spreadsheets/d/1sE779yof5iWkTv6vuQj7XRjGRnVICvaRXiNMlr9hfUs/edit?usp=sharing

Please note that these schools should not be disabled on production till product Confirms.

It should only be disabled in Staging as of now. I will confirm the date for PROD

cc @karntrehan

**Comment by karntrehan** [comment]
To be picked post v2.3.4 is deployed to 100% usrs and force updated.

**Comment by karntrehan** [comment]
Closing as go ahead from PT for prod deployment has not been recieved. To be picked separately.
