### ISSUE TITLE
Ingestion of 1000 sets

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#207]
**Goal:** Ingest 1000 more sets of questions into the App

**Acceptance Criteria:** New sets of questions show up in the App for teacher flow

**Telemetry Information:** None specific

**Test Cases:**

- Login through teacher flow and questions show up in front end of the app.
- When I open through examiner and mentor flow, these new questions should not show up

**Comment by rohitsamagra** [comment]
- 300 sets

**Comment by rohitsamagra** [comment]
@Ajay-Maury input shared from Snehi

https://docs.google.com/spreadsheets/d/1KAuxYh0TMs6fMCn1g80tWx07WDAV4zVR96s8jmOqvK8/edit#gid=0

**Comment by rohitsamagra** [comment]
- Tushar to setup repo's for Ajay

**Comment by charanpreet-s** [comment]
@rohitsamagra to get updated format of forms in excel from PT

**Comment by rohitsamagra** [comment]
@karntrehan Can you confirm if this ticket can be scoped at Eng end now? Thanks

**Comment by rohitsamagra** [comment]
- JSON format is not required once moved to NISAI?
- Snehi discuss with Ankit on changing format

**Comment by karntrehan** [comment]
Getting delayed as PT needs to clean up questions

**Comment by rohitsamagra** [comment]
@karntrehan update from PT - will share ~1000 questions by 5th Jun (500 of these will be shared by 3rd)

Hope we can pick it in 2412

**Comment by charanpreet-s** [comment]
@tushar5526 to discuss with Snehi

**Comment by rohitsamagra** [comment]
1. Auto-tune working 
2. Creating new competencies for teacher flow (currently, examiner competencies are different, but mentor+teacher competencies are combined, wanted to understand if we can create separate competency flow for teachers and mentors?)
3. Scoping out the randomiser formula 
4. JSON format for ingestion (shared with Ajay, Tushar and you)

**Comment by rohitsamagra** [comment]
- Check with PT as to why they gave auto-tune questions

-- Test using Auto-Tune for PT

- Give postman collection to PT and ask them to play around and let us know if it working fine - setup a call with Snehi - use the postman collection - walk through the flow in the evening

- Create a seperate ticket for randomiser (huge effort)

**Comment by amit-s19** [comment]
Final JSON created, questions yet to be ingested on dev.

**Comment by rohitsamagra** [comment]
- JSON
- Ingested on Dev
- Ajay to share with Aakash in first half (1000 questions)
- Ajay will share ref id's with Aakash on NL Backend (Ajay to check with Snehi on NL Competency ID mapping)
- Aakash - test on staging - test on dev will start today
- Push to Prod (2-3 days before actual)

**Comment by karntrehan** [comment]
Passage content not visible on Android. @charanpreet-s to check.

**Comment by charanpreet-s** [comment]
Form upload to be done in next week

**Comment by VargishChauhan** [comment]
Bug : For some set, 8 questions are coming.

**Comment by tushar5526** [comment]
Ingestion on staging done. Tested by @AakashSatpute119
