### ISSUE TITLE
Samvad Admin Portal - Update

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#209]
- Remove uploading ODK files, user should be able to add message in front end, upload any files and send out
- Static Bot Icon of Nipun Laskhya Logo

![Image](https://github.com/Mission-Prerna/nl-apis/assets/145356240/74078f6d-5047-442a-aa79-27c6b2bb961e)

**Comment by geeky-abhishek** [comment]
@karntrehan  can you add ankit (githubid-ankitmlesmagico) to the board?

**Comment by karntrehan** [comment]
## Suggested flow

The 2 screen flow for bot creation continues to exist, but with simplications. 

### Screen 1

![Image](https://github.com/Mission-Prerna/nl-apis/assets/5885669/f56d9405-7bb3-4cdd-a13d-40a999718d4e)

*Remove*: 
1. Conversation description - Automated from conversation name
2. Purpose of conversation - Automated from conversation name
3. Start Message - Automated from conversation name
4. Start date - Current date

*Update*:
1. Default Bot Icon to be added
2. Segment id to be a dropdown of existing segments
3. Or functionality to upload excel and create segment

*API requirements*
1. Segment List API - @Ajay-Maury 
2. Create segment API - @Ajay-Maury 

### Screen 2

![Image](https://github.com/Mission-Prerna/nl-apis/assets/5885669/5f00c14f-dc48-4202-a426-eccdca7ca386)

*Add*
1. "Add simplified logic" button next to existing "Add Logic" button

![Image](https://github.com/Mission-Prerna/nl-apis/assets/5885669/109b809e-69bf-412e-bb1e-48c15c830aa4)

*Update*:
1. Name - Notification title
2. Description - Notification description

*Add*:
1. New pop similar to above pop up which has - Notification title, Notification description, Content & file (optional)
2. On submit - Replace content and file in preexisting ODK file XML and carry on with the existing bot creation flow. 

*Dependency*:
1. ODK file to be used to replace content and file. - @karntrehan

**Comment by karntrehan** [comment]
# WIP
## Segment List API 

### GET(/segments)
Header - Admin Token

### Response 

**Success**
```json
[
  {
    "id": 1,
    "name": "All teachers",
    "description": "Segment for internal engineering testing",
    "created_at": "2023-03-03T15:10:01.711001+05:30",
    "updated_at": "2023-03-03T15:10:01.711001+05:30"
  },
  {
    "id": 2,
    "name": "All mentors",
    "description": "Segment for internal engineering testing",
    "created_at": "2023-03-03T15:10:01.711001+05:30",
    "updated_at": "2023-03-03T15:10:01.711001+05:30"
  }
]
```

**When no segments configured**
```json
[]
```


## Create Segment

### POST(/segment/phone)
Header - Admin Token

### Request

```json
{
  "segment_name": "Segment for bot: $botName",
  "segment_description": "Autogenerated by admin panel for bot: $botName",
  "phone_numbers": [
    "9876543210",
    "2109876543"
  ]
}
```

### Response 

**Success**
```json
{
  "count": 2,
  "segment": {
    "id": 199,
    "name": "Segment for bot: $botName",
    "description": "Autogenerated by admin panel for bot: $botName",
    "created_at": "2023-03-03T15:10:01.711001+05:30",
    "updated_at": "2023-03-03T15:10:01.711001+05:30"
  }
}
```

**Error**
```json
{
  "error_code": "ERROR_2002",
  "error_message": "Invalid request format"
}
```

**Comment by Ajay-Maury** [comment]
PR:- https://github.com/Mission-Prerna/uci-chatbot-helper/pull/18

**Comment by Ajay-Maury** [comment]
> PR:- [Mission-Prerna/uci-chatbot-helper#18](https://github.com/Mission-Prerna/uci-chatbot-helper/pull/18)

Deployed in Staging env

**Comment by karntrehan** [comment]
@rohitsamagra to test

**Comment by rohitsamagra** [comment]
- Any staging app with staging admin panel
- Already pushed to Prod (segment 1) - @AakashSatpute119 and @rohitsamagra to discuss and test

**Comment by rohitsamagra** [comment]
@AakashSatpute119 

1. We'll fill out the Mobile Number, Segment Creation (Yes/No), and if Yes, then the Segment Name in the Excel format.
2. In the backend, the Mobile Number will be linked with the District Name, Block Name, Person's Name, Designation, and School UDISE Code.

**Comment by AakashSatpute119** [comment]
Bug : 
- [ ]  1. In the segment dropdown only 3 segments are showing may be segment API is not integrated.
https://prnt.sc/kYj0_VregtJO , https://prnt.sc/AFlH1g6gQp_U

**Comment by charanpreet-s** [comment]
@karntrehan  to check for the issues

**Comment by AakashSatpute119** [comment]
Tested on staging working fine. To be deploy and test on prod.

**Comment by charanpreet-s** [comment]
To be deployed to Prod by @Ajay-Maury  today and tested by @rohitsamagra

**Comment by Ajay-Maury** [comment]
> To be deployed to Prod by [@Ajay-Maury](https://github.com/Ajay-Maury) today and tested by [@rohitsamagra](https://github.com/rohitsamagra)

BE deployed on prod.

**Comment by AakashSatpute119** [comment]
Tested on prod everything is working fine.
