### ISSUE TITLE
Onfield Issues

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#218]
- [x] Mentor Issues: https://docs.google.com/spreadsheets/d/1vOa3q2m9gNCn9NWd4JxrOkjLv4EMw0AtSR4bd81snjU/edit#gid=0
- [x] Question loading issues (2412): (screenshots) - see if recreatable and update PT 
https://docs.google.com/spreadsheets/d/1wIoFFfaSb4Fvs0WJG3dUTiaVtQuZhwc_xiwnspsZSJ4/edit#gid=876569076
- [x] Questions are in a gibberish format
- [x] Add ending assessment option for mentor flow after assessment of 5 students are done: (do you want to end the assessment or do you want to proceed? ) https://docs.google.com/spreadsheets/d/1wIoFFfaSb4Fvs0WJG3dUTiaVtQuZhwc_xiwnspsZSJ4/edit#gid=876569076 
- [x] Issue of mentor opening the app (problem in mapping)
- [x] No chats loaded

**Comment by karntrehan** [comment]
@rohitsamagra and @AakashSatpute119 to collaborate on this

**Comment by tushar5526** [comment]
No update from PT and PM

**Comment by tushar5526** [comment]
Aakash resolving issues that are getting shared on group - but nothing has been added on the sheet.

**Comment by charanpreet-s** [comment]
@AakashSatpute119 in discussion with VSK to check for the block to validate the issues

**Comment by AakashSatpute119** [comment]
Tracking sheet : https://docs.google.com/spreadsheets/d/1vOa3q2m9gNCn9NWd4JxrOkjLv4EMw0AtSR4bd81snjU/edit#gid=1316099007

**Comment by karntrehan** [comment]
Awaiting confirmation from ground.

**Comment by tushar5526** [comment]
@rohitsamagra to check on the last 2 issues.
