### ISSUE TITLE
Mentor API Updation

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#219]
**Goal:** Update "mentor assessments API" to show students

**Acceptance Criteria:** Technosys to be able to access student level data in mentor assessments API

**Telemetry Information:** None specific

**Test Cases:** Access the API and should be able to access student level data as part of mentor assessments API

**Comment by rohitsamagra** [comment]
@karntrehan Updated this ticket - please let me know if I need to give more clarity here - thanks

**Comment by Ajay-Maury** [comment]
@rohitsamagra Can you please elaborate more, what do you mean by `should be able to access student level data as part of mentor assessments API`
do we need data like :- 
```json
[
    {
        "assessment_data": {
            "block_name": "Achhnera",
            "class": 1,
            "created_at": "2024-02-10 12:16:14.272",
            "district_name": "AGRA",
            "phone_no": "9997883967",
            "result": "NOT NIPUN",
            "student": {
                "gender": "female",
                "name": "Rashi kumari",
                "roll_no": 7509,
                "unique_id": "038264384"
            },
            "udise": 9150200401,
            "user_type": "teacher"
        }
    },
    {
        "assessment_data": {
            "block_name": "Achhnera",
            "class": 1,
            "created_at": "2024-03-09 11:27:42.86",
            "district_name": "AGRA",
            "phone_no": "6397686718",
            "result": "NIPUN",
            "student": {
                "gender": "female",
                "name": "Rashi kumari",
                "roll_no": 7509,
                "unique_id": "038264384"
            },
            "udise": 9150200401,
            "user_type": "teacher"
        }
    }
]
```

**Comment by karntrehan** [comment]
Single API to be shared for both mentor and teacher. If student ID not available NULL to be sent @Ajay-Maury

**Comment by tushar5526** [comment]
PR up by Ajay.

**Comment by Ajay-Maury** [comment]
Deployed to Prod.
curl:-
```json
curl --location 'http://103.154.251.109:8000/data/student-assessment-data?limit=10&offset=0&from_date=2022-01-01&to_date=2034-02-01&actor_type=mentor' \
--header 'Authorization: Bearer <auth-token>'
```
In this actor_type query is optional, It can be used as an actor filter like actor_type=mentor or actor_type=teacher  or anything else.

**Comment by rohitsamagra** [comment]
- Aakash to test
- Share curl with Snehi and let them know the changes - Rohit to share

**Comment by AakashSatpute119** [comment]
-  In assessment tabel able to lots of assessments with `student_id = NULL` but in API it is not returing those students assessment in response.
- Also table which we are using currently to get this data `assessment_result_nl_dashboard_v2`not contain any NULL student_id data.


![Image](https://github.com/Mission-Prerna/nl-apis/assets/132545585/fad887d3-82dd-4dd5-9c62-3e72103761f3)


![Image](https://github.com/Mission-Prerna/nl-apis/assets/132545585/8be4cdb6-1cd6-4189-b833-27435bcc4563)



![Image](https://github.com/Mission-Prerna/nl-apis/assets/132545585/a3fcc269-ec79-43f1-b7ac-e1ae567e1ef6)
