### ISSUE TITLE
[Examiner Flow] Audio enhanced through Mascot before the start of the assessment

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#221]
**Goal:** Audio enhanced through Mascot before start of the assessment

**Acceptance Criteria:**
- When an examiner clicks on student to start the assessment, the mascot comes up and calls the students name
- Timing to be as along it speaks with 200-300 milliseconds before starting and ending
- GIF with existing tittu bird
- Text will - Full Name aakalan ke liye aajaiye (in Hindi)
- Text should be center aligned
- Time out of 5-7 seconds to send to next screen in case of any errors

**Telemetry Information:** None specific

**Test Cases:** 

- Login through examiner flow and select a student and the mascot should call the correct student name

Requirements: https://docs.google.com/document/d/1E10QprmncX8k3NqUn3PvbGakGnxaGqEV57dypGDbtAI/edit
Design: https://www.figma.com/design/KEv3Bga4hygJiw4QPFMxx3/NL-App_May_2023?node-id=3382-664&m=dev

**Comment by rohitsamagra** [comment]
- Move to next sprint
- Local T2S on Android

**Comment by amit-s19** [comment]
@charanpreet-s  to review this

**Comment by rohitsamagra** [comment]
PR rasied: Harsh to include the number:

**Comment by charanpreet-s** [comment]
@charanpreet-s to check for PR

**Comment by rohitsamagra** [comment]
- Harsh fixing bugs and to be shared with Aakash

**Comment by karntrehan** [comment]
Issue on Xiomi / RedMi - To be checked again.

**Comment by charanpreet-s** [comment]
@rohitsamagra to check on his device and add comments here

**Comment by tushar5526** [comment]
Tested on prod build.
