### ISSUE TITLE
Sharing raw data with CSF

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#227]
**Goal:**

CSF wants to access the raw data of NLApp for certain analysis since they are working on certain parts of the NBC program

**Acceptance Criteria:**

- CSF should only be able to access select columns in the raw assessments table
- It is available as a read-only access

**Telemetry Information:** 

- Know when and what all data CSF accessed

**Test Cases:**

- Should not be open for anyone else to access
- Only people who have access should be able to access

**Requirement:**

- Need Number of questions asked within a competency and how many were correct (raw data) along with Student ID
- Remove to subject-id and keep subject name
- Keep mentor_id along with mentor name
- Remove actor_id get actor type which is teacher or mentor or examiner or etc.
- District Name and Block Name (remove block_id)
- Remove assessment_type_id
- Remove submission_timestamp and submission_at
- Remove app_version_code
- Remove student_name
- Keep competency Id and get name
- Remove statement
- Remove "is_network", "workflowref_id", "old_assessment_id", "old_student"id", "is_valid", "updated_at"
- For mentors show student session and student ID
- Time range: Oct 2023 onwards

**Proposed data to share:**
- Assessments table along with mapping of competency Id to name from work flow ref id table

Other details: 

- CSF Metabase: https://csf.metabaseapp.com/

Open questions:
What?
- Will we need to share data of only teacher flow or examiner flow and mentor flow as well? - data of all actors
- What all columns need to be shared?
- Which is the date at which assessment was taken "created_at"? Yes - created_at is date at which assessment is taken

How?
- How do we usually connect metabase to Hasura?
- Sharing API would be appropriate in this context?

**Comment by rohitsamagra** [comment]
Read access

- Mentor Table
- Actor Table
- Student Table
- Assessment visit 
- Assessment detailed

**Comment by rohitsamagra** [comment]
Basis our discussion had a call with Karan and Tushar. Need below confirmations today so that we can finish this tomorrow.

Approach 1
- We will be able to give them access to the below raw tables with one day of effort. As discussed we will not be able to remove fields/rename as we discussed
- Assessment Visit without date filter (below tables so that they can pull relevant information)
- Mentor Table
- Actor Table
- Competency Table
- District Table
- Block Table
- Subject Table

Approach 2
Alternate approach is to create an MV which is ~3 days of effort and it would need computation at our end since we have to pre-calculate certain fields. MV are good if they frequently query our data

Also, do we have an estimate on how often will they query the data?

Suggestion from XT would be to give them access to raw data, monitor their usage, basis load - if heavy, would be good to move to MV

Please confirm if we can go ahead with approach 1 and if any other table is required in approach 1

Thanks, Rohit. I think approach 1 sounds good - basically they'll have to join tables at their end to procure the required columns? This sounds okay. However, could you please clarify what 'without date filter' means - as in the date column won't be there or separate quarterly files won't be there?

They might query it for their own analysis, which might be a little frequent right now, and then eventually settle down later. But good idea to give them raw data, monitor their usage and then decide basis that. Let's do that

**Comment by charanpreet-s** [comment]
@karntrehan  to discuss this with Snehi. We to provide only creds for the db
