### ISSUE TITLE
Clean up difference between staging and prod competency ID

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#228]
**Goal:** Staging should be exact replica of Prod

**Context and Problem Statement:** 

Question: Who will be best person to check why we had created so many competency ID's in the past?

- Competency ID table: 

There are many other form ID's apart from our relevant ID's on Prod. Below are the relevant competencies in the app along with GRA: Grade 2 Hindi: 304, Grade 3 Hindi: 308

Examiner GRA: Grade 2 Hindi: 154, Grade 3 Hindi: 158

![Image](https://github.com/Mission-Prerna/nl-apis/assets/145356240/4f9ab6a0-2d26-41d9-84e0-44e79347d6ff)

![Image](https://github.com/Mission-Prerna/nl-apis/assets/145356240/1bb3fd3a-83fe-4d0c-962c-f62303d5c3e0)

- Ref ID Table: 

Staging ID's are different from Prod. Staging has very low count of form ID's

(copy prod and move to staging)

Update Prod ID's into the staging

**Solution**:

- Make a copy of Prod - replicate it on staging
- Clean up staging, test it and change prod to the updated staging copy

**Steps**:
- [ ] Ajay to deploy Prod data on staging
- Aakash to clean up of forms 
- ODK Forms to be removed along with competency ID

**Acceptance Criteria:**

- Staging and Prod are exact replica's with only relevant competency ID

**Test Cases:**

- Open Prod and randomly check with staging for a few ID's

**Comment by rohitsamagra** [comment]
@karntrehan 

Scope added to this ticket by @AakashSatpute119 and me

@Ajay-Maury can you take a look and let us know in case of any questions.

Also, @karntrehan any idea on - we have 109 Competency ID's in prod with ~20 actively being used - can we delete the rest?

**Comment by charanpreet-s** [comment]
@AakashSatpute119  to calculate the number of forms from prod competencies mapped to refs ids

**Comment by Ajay-Maury** [comment]
Stag data of tables `workflow_refids_mapping` and  `competency_mapping`  updated with prod data.

**Comment by AakashSatpute119** [comment]
![Image](https://github.com/Mission-Prerna/nl-apis/assets/132545585/f3620a56-2d70-4a77-bb40-4f25d1f021bd)

Sheet link : https://docs.google.com/spreadsheets/d/1-0M0-RlQX422Hn8Gcua7PY2GWOqFeRz0uhl4IMmt6fA/edit?usp=sharing

**Comment by AakashSatpute119** [comment]
**Steps on Staging** 
- [ ]  Find number of competancies which are currently in use. (unsed competancies are suchi (week based competencies))

- [ ] Remove unused suchi competencies. 

- [ ] Remove ref_id mapping for this unused competencies.

- [ ] Get list of unused forms from suchi compentencies and delete. 

- [ ] Test on app assessment flow is working fine. 

**Steps on Prod**
Approch 1 : We can dump staging data on prod for the compentancy mapping and ref_id tables.
Approch 2 : Do the same steps which are done on staging.

**Comment by rohitsamagra** [comment]
- Aakash to make changes in Prod

**Comment by charanpreet-s** [comment]
Verified by @AakashSatpute119 , on ODK forms are deleted which are not in use(not in mapping)
