### ISSUE TITLE
NL server getting down between 2-3pm daily

### ISSUE THREAD

**Issue by Ajay-Maury** [Mission-Prerna/nl-apis#231]
NL server getting down between 2-3pm daily
https://discordapp.com/channels/959457910604333107/1080382870910140457/1242403907855056907

**Comment by rohitsamagra** [comment]
- Issue to be diagnosed if it is on NL front or uptime front
- Tushar to ask Karun to add NL Server on a different uptime

**Comment by tushar5526** [comment]
![Image](https://github.com/Mission-Prerna/nl-apis/assets/30565750/01769785-80ff-4712-969e-27529266f46f)

**Comment by Ajay-Maury** [comment]
Observation of uptime kuma server down response from 19th June till today (24th June 11 am) 

- On 19th June,  Posthog Telemetry and NL service went down at `2:35 PM`, with no down alert for NL KONG. (https://discord.com/channels/959457910604333107/1080382870910140457/1252912184657313852)

- On 20th June,  Posthog Telemetry and NL service went down at `2:37 PM` & `2:44 PM`, with no down alert for NL KONG. (https://discord.com/channels/959457910604333107/1080382870910140457/1253274908658503701)

- On 21st June, no downtime alerts

- On 22nd Posthog Telemetry and NL service went down at `2:40 PM`, with no down alert for NL KONG. (https://discord.com/channels/959457910604333107/1080382870910140457/1254000567290953741)

- On 23rd June Posthog Telemetry and NL service went down at `2:36 PM`, with no down alert for NL KONG. (Posthog Telemetry and NL service went down at 2:37 PM & 2:44 PM, with no down alert for NL KONG. )

**Comment by Ajay-Maury** [comment]
Received  Notification on uptime Kuma:- 
![Image](https://github.com/Mission-Prerna/nl-apis/assets/97455068/c89a9408-6b84-4bb6-bb15-66295ce75c14)


## After observation, I reached the point that:- 

- Only Posthog Telemetry service is getting down daily. 
![Image](https://github.com/Mission-Prerna/nl-apis/assets/97455068/39e2e9b2-d96e-4f61-a106-5164e180ade9)

- The ` Your service NL went down. ` alert coming because, `Posthog Telemetry` is a child of ` NL` group on uptime kuma, & group notification was also on, I closed it and will verify once again the down alert received.

## Below is the Observations of the recent 6 hours (12 pm to 5 pm)
- NL & kong did not go down since 19th of June. 

NL:-
![Image](https://github.com/Mission-Prerna/nl-apis/assets/97455068/338ab717-91b8-48fb-bef9-2557edb14840)

Kong:- 
![Image](https://github.com/Mission-Prerna/nl-apis/assets/97455068/c8956d40-e25b-48b0-bf61-a64aae0c6906)

- Only Posthog goes down daily

![Image](https://github.com/Mission-Prerna/nl-apis/assets/97455068/87fd137d-a28c-484c-a29d-736742fdf83a)

**Comment by Ajay-Maury** [comment]
- [x] Top-level item
  - [x] Nested item 1
  - [ ] Nested item 2
    - [x] Sub-nested item A
    - [ ] Sub-nested item B

**Comment by tushar5526** [comment]
We have increased the number of plugin workers for PostHog. Try scaling the web vertically to handle spikes.

**Comment by karntrehan** [comment]
Posthog's internal clickhouse is maxing out the server. As the downtime is limited, we can ignore this for now.
