### ISSUE TITLE
Diet led assessments - pop up towards the end of assessments v2

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#232]
Goal: Examiner should see a pop-up towards the end of assessments which flags any inconsistencies and also asking him to verify that he did it correctly

Acceptance Criteria: All checks done, the flags raised and pop-up shows up

Telemetry Information: None

Test Cases: If I login as an examiner, based on different scenarios I meet, only the relevant scenario messages should come up and I should have an option to check the option

Requirements document: https://docs.google.com/document/d/1m0D2KBvDv7qswaqL3XB_YbJrGqsO5ZvEHrc74FOmc60/edit

Updated design: 

https://www.figma.com/design/KEv3Bga4hygJiw4QPFMxx3/NL-App_May_2023?node-id=3274-648&t=xhUTlRkw5QVNSlzq-0

**Comment by rohitsamagra** [comment]
- Harsh to complete today and raise PR

**Comment by rohitsamagra** [comment]
- Harsh to make changes in the code and raise PR
- To be done by end of the day

**Comment by charanpreet-s** [comment]
@charanpreet-s  to check for PR

**Comment by rohitsamagra** [comment]
@karntrehan in examiner flow, do not allow submissions on Sunday is the input from Ujjwal which we can factor in whenever possible - will add it to the ticket of pop-up towards end of assessments

**Comment by rohitsamagra** [comment]
- Discuss with Karan on the working of do not allow submissions on Sunday (what happens when an assessment is done on Saturday and submitted on Monday?)
