### ISSUE TITLE
[Examiner Cycle] Image Capturing for Anti-Cheating

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#236]
**Goal:** As part of Anti-cheating for the examiner cycle, to avoid impersonation of students, we want to add deterrents in the existing examiner flow. As part of it, image capturing will be developed to act as a deterrent within the flow.

**Acceptance Criteria:**

- As an examiner, I should be able to start an assessment and image capturing should show up at the start of assessment
- As an examiner, I should be able to start an assessment and image capturing should show up after I finish a particular competency assessment
- As an examiner, I should be able to start an assessment and image capturing should show up after I finish all competencies assessments
- As an examiner, I should be able to start an assessment and image capturing should not show up for all students

**Success Metrics/Telemetry Information:**

- Telemetry: Capture how many times the image capturing screen shows up
- Success Metrics: Subjective sense of reduction in impersonation by half due to the additional deterrent added in

**Test Cases:** 

- Open examiner flow and start assessments for all students across grade
- Image capturing should show up randomly basis the randomizer defined in the back end - shows up for x% of students and shows in the order of at the start of assessment followed by after a particular competency followed by results screen

Requirements Document: https://docs.google.com/document/d/1Y-al7sD-KxyUd34tBfd2TsaPlMQ9qYUCZYubcOJ1PGM/edit
Design: https://www.figma.com/design/viU7EdVpIDwmq38uWMgxC2/Nipun-Bharat-AI?node-id=100-1539&t=vM2ljPvYhcgFioI3-0

**Comment by karntrehan** [comment]
To be completed today.

**Comment by rohitsamagra** [comment]
- Should show at start or at the end (40% at the start, 40% at the end, 20% at the both)

**Comment by rohitsamagra** [comment]
- assess 30 students - 40% before, 40% after - 24 students will be shown the image capture, if 4-5 are absent, not show up for them, it will show up only for the rest - the rest 6 for which we were not going to show the image capture are present

**Comment by tushar5526** [comment]
@AakashSatpute119 is testing this.

**Comment by tushar5526** [comment]
Tested on prod build.
