### ISSUE TITLE
Migration of caching package from nestjs/common to nestjs/cache-manager

### ISSUE THREAD

**Issue by Ajay-Maury** [Mission-Prerna/nl-apis#237]
- Migration of caching package from `nestjs/common` to `nestjs/cache-manager`  as caching is deprecated in `nestjs/common `
- Mentorinsightperformance API

**Comment by Ajay-Maury** [comment]
deployed on staginig

**Comment by amit-s19** [comment]
@AakashSatpute119  to test this

**Comment by rohitsamagra** [comment]
- @AakashSatpute119 tested and you want to verify if the beavior is corrrect - to recheck with @Ajay-Maury

**Comment by AakashSatpute119** [comment]
Rechecked with @Ajay-Maury it is working as expected.

**Comment by rohitsamagra** [comment]
- to be moved to Prod today
- Tested on Prod and close the ticket

**Comment by rohitsamagra** [comment]
- Build to be shared today

**Comment by Ajay-Maury** [comment]
> * Build to be shared today

Deployed on Prod
cc:- @AakashSatpute119

**Comment by charanpreet-s** [comment]
Tested on Prod
