### ISSUE TITLE
Product + Tech Scoping - UCI Admin UI/UX Update - v2

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#238]
**Requirements:**

**Bucket Name** (Needs to be figured out)
- [ ] Show Dropdown with existing Bucket Names and option to create new bucket name

**Recipient List**
- [ ] Give template to download of excel
- [ ] Uploading using phone numbers and segment names

**Segment Selection**
- [ ] Send bots to different segments in one go
- [ ] Type and select the segments (reconfirm if segment name is possible)

**Simplified Logic Page:**
- [x] Rename "Add Simplified Conversation Logic" to "Add Simplified Logic"
- [x] Remove button of "Upload Form"
- [x] Change button which says "Add" to "Send"
- [ ] Adding a new line
- [ ] Adding hyper link

**Deprioritized:**
- [ ] The content tab should be similar to gmail with various necessary tools to format the text. You can refer to figma design shared by me earlier. Right now I am unable to format the text. We were not able to use features such as new paragraph, bold, italics etc.

**Clarifications:**

- Is it possible to write the same conversation name in another msg if I am sending the msg to some other segment?
Ans: Possible, if we have multi-select for segments built in

- What’s the use of create broadcast msg checkbox and what if I don’t select it
Ans:

Longer Term/User Lens

**Segmentation Management**

- [ ] Have another screen for creating segments
- [ ] Write Segment name in text view
- [ ] Upload excel file with phone numbers
- [ ] Given option to download template of Excel

**Comment by rohitsamagra** [comment]
- Needs high investment techincally
- ROI/Prioritize

**Comment by charanpreet-s** [comment]
@rohitsamagra @karntrehan @VargishChauhan To work on updating the scope as per discussed in Pragati

**Comment by rohitsamagra** [comment]
- Cohorting → done through excel
- Survey enabled → Enabling survey through simple text like google form
- Dashboard → Real time
- Nuding and tracking → do scoping and tech feasibility → v1 retrigger everyone at once

**Comment by tushar5526** [comment]
Priority to be finalised by today

**Comment by karntrehan** [comment]
Analysis completed: https://docs.google.com/spreadsheets/d/1eI4cwEOGIKAJ0Vfc5tfysxbRBLJuvFVdIFci81nvsmY/edit?gid=0#gid=0

Discussion to be had with PT.

**Comment by karntrehan** [comment]
PT discussed closed. Plan aligned basis https://github.com/Mission-Prerna/nl-apis/issues/238#issuecomment-2201974840. Tickets to be created by @VargishChauhan and @karntrehan . This ticket to be closed.
