### ISSUE TITLE
Create separate competencies for teacher/mentor

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#240]
Creating new competencies for teacher flow (currently, examiner competencies are different, but mentor+teacher competencies are combined, wanted to understand if we can create separate competency flow for teachers and mentors?)

**Comment by AakashSatpute119** [comment]
Our logic to get competencies is based on the learning outcomes of both teachers and mentors having the same prefix "Nipun Lakshya:". It may require some changes from the backend.

**Comment by rohitsamagra** [comment]
- Ajay to check how to proceed and update - go ahead with ID 
- Move existing one's into the existing logic
- Check if we can proceed with the approach of "Prefix"

**Comment by charanpreet-s** [comment]
Adding quick fix as going ahead with prefix approach- "Mentor-"

**Comment by karntrehan** [comment]
Not required anymore.
