### ISSUE TITLE
Student Update API

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#242]
- Discussion with Technosys

For context, they wanted to understand the delete function for the student list NL API (so basically there are 3 activities that can happen with a student: either they get added (simple), or they get promoted (simple), or they get deleted (this he was confused about).

**Comment by karntrehan** [comment]
POA: 

- [ ] Ask for data dump 
- [ ] Add reminders to update data weekly.

**Comment by rohitsamagra** [comment]
- Email from Snehi on 400 errors 
- @tushar5526 to run at his end
- @tushar5526 to schedule call with Snehi

**Comment by karntrehan** [comment]
Confirmed with Technosys. Working fine.
