### ISSUE TITLE
Tech Scoping - RCT Readiness.

### ISSUE THREAD

**Issue by rohitsamagra** [Mission-Prerna/nl-apis#246]
https://github.com/orgs/Mission-Prerna/projects/2/views/2?pane=issue&itemId=63491098

BE:

- [x] Create a table containing disable school<>actor mapping 
- [x] Add is_active field in school API handling only for teachers
- [x] Neglect submissions from teachers post blacklisting of school. 

Subtasks:

- [x] Handle disable flow, add toast on start assessment button for disabled teachers(for now handling for teachers flow only)
- [x] Update Room DB and migrate
- [x] Remove Realm tables

**Comment by charanpreet-s** [comment]
Approach Taken : 

1. Handling will be done at the school level. 
2. Schools will be disabled from BE. A blacklist table with Actor<>School Mapping will be created.
3. In the existing user API v2 there will be an additional field of "isActive"
4. Android will consume this, and halt flows for respective schools

@tushar5526 to confirm

**Comment by tushar5526** [comment]
Need clarifications on what will happen on the home screen when a school is disabled for different actors.

**Comment by tushar5526** [comment]
Flow to only run for teacher users. Examiners and mentors stay unaffected.

**Comment by tushar5526** [comment]
@VargishChauhan to check with PT whether there is a need for a pop-up notification for disabled actors for a specific school.

**Comment by charanpreet-s** [comment]
Deployed on Staging. 
``Neglect submissions from teachers post blacklisting of school.```
Yet to be picked today by @Ajay-Maury

**Comment by TheNPDev** [comment]
https://drive.google.com/file/d/10jRw73Vq0d21bWhLO8W9c-qmArJMit4y/view?usp=sharing

Build for testing

**Comment by AakashSatpute119** [comment]
> https://drive.google.com/file/d/10jRw73Vq0d21bWhLO8W9c-qmArJMit4y/view?usp=sharing
> 
> Build for testing

`BUGS`

- [ ] 1.Teacher : App crashes on " विद्यालय के सभी आकलन का सारांश "

https://go.screenpal.com/watch/cZihQxV8kFv

- [ ] 2.App crashes on download forms : https://go.screenpal.com/watch/cZihQzV8kq2

**Comment by charanpreet-s** [comment]
SUbmission API change deployed on staging 
@charanpreet-s to check with @TheNPDev on the forms issue

**Comment by TheNPDev** [comment]
Release build of 2.3.3 on staging : https://drive.google.com/file/d/11DyQ056Y7OAzAXo6mfjJ_-L4NgMnKOgh/view?usp=sharing

Release build of 2.3.4 on staging : https://drive.google.com/file/d/11DIxahNizAhQk_kYcJmaZI_hWBbq1q7v/view?usp=sharing

@AakashSatpute119 Please test it for migration

cc: @charanpreet-s

**Comment by karntrehan** [comment]
API to be deployed to prod today. Prod pointing build to be shared for testing.

**Comment by dhruv-1001** [comment]
APK shared. Devbox to be undertaken tomorrow.

**Comment by VargishChauhan** [comment]
@TheNPDev 
Below is the message we need to show to the teachers
"आपके विद्यालय में जुलाई 2024 से मार्च 2025 तक आकलन सेवाएँ बंद कर दी गई हैं।"

**Comment by dhruv-1001** [comment]
Tracked in this [ticket](https://github.com/Mission-Prerna/prerna-lakshya-app/issues/478)
