### ISSUE TITLE
[Ad Hoc] NBMC API error

### ISSUE THREAD

**Issue by Ajay-Maury** [Mission-Prerna/nl-apis#257]
Student id is being sent as NULL in NBMC API. (https://discord.com/channels/959457910604333107/1258696524851052677/1258696564252217396)

The NL data API for NBMC should have (from April 2024 onward):
- in teacher data - student id (without null)
- in mentor/spot data - student id (not student session)

**Comment by Ajay-Maury** [comment]
@charanpreet-s  to check the analysis

![Image](https://github.com/Mission-Prerna/nl-apis/assets/97455068/d1c3a0b8-e749-448b-b634-8714ef5e7358)

Query:- 
```
SELECT count(*),
    app_version_code,actor_id
FROM assessments 
WHERE student_id IS NULL
GROUP BY app_version_code,actor_id
ORDER BY app_version_code DESC 
```

**Comment by karntrehan** [comment]
Android sending null for student Id. @charanpreet-s to check.

**Comment by AakashSatpute119** [comment]
Tobe pick today.

**Comment by charanpreet-s** [comment]
Older detailsselection screen is still getting hit, trying to debug in which scenario it is getting started

event - nl-detailsselectionscreen-nextbutton-click

**Comment by karntrehan** [comment]
Old flow somehow was still getting triggered till 2.3.3.1, the count was low, but is still getting used, with the last release of 2.3.4 we have around 50K installs 0 events for student id null, the major reason is removal of realm in previous release, and this release also has removal of detail selection screen, means this wont happen again and soon we will be force pushed to RCT. 

Stopping the analysis here.
