### ISSUE TITLE
BE [BUG] - Assessment Cycle Creation Includes Deleted Students.

### ISSUE THREAD

**Issue by AakashSatpute119** [Mission-Prerna/nl-apis#259]
BUGS
- [x] At time of creating assessment cycle code should pick only those students which are active(deleted_at =null ) but currently it is select random students with deleted students in cycle.

- [x] Getting inactive (deleted students) students in `/api/school/9150204901/students` API

- [x] Getting inactive (deleted students) students in `api/school/9150204901/students/result?grade=1,2,3&cycle_id=6` API

**Comment by AakashSatpute119** [comment]
Tested on staging,Deploy on prod and test is pending.

**Comment by Ajay-Maury** [comment]
PROD PR:- https://github.com/Mission-Prerna/nl-apis/pull/258

**Comment by dhruv-1001** [comment]
To be tested on Prod.

**Comment by AakashSatpute119** [comment]
Tested on prod working as expected.

**Comment by karntrehan** [comment]
Deployed, tested, closed.
