### ISSUE TITLE
Examiner credentials

### ISSUE THREAD

**Issue by VargishChauhan** [Mission-Prerna/nl-apis#260]
For new Examiners , we will need new set of credentials

- [x]  Get credentials from PT  
- [x] Invalidate all existing examiners
- [x] Ingest Examiners into the backend system

**Comment by Ajay-Maury** [comment]
Sample examiner CSV:- 

[sample-examiner-ingestion.csv](https://github.com/user-attachments/files/16490890/sample-examiner-ingestion.csv)

**Comment by VargishChauhan** [comment]
This will come in two sets. 

1st set :  Mentor [details](https://docs.google.com/spreadsheets/d/1nS7rAYyS2-MSLdCVD11alM_tmTSFtW7tUG12OaZ1Ma8/edit?gid=0#gid=0)

2nd set: To be shared by 30th August


Also, many of the examiners details are already present in our system.

**Comment by VargishChauhan** [comment]
@Ajay-Maury  We will take this only when we receive all 70 District data from PT . Till then it will be in blocked stage

**Comment by karntrehan** [comment]
Linked to https://github.com/Mission-Prerna/prerna-lakshya-app/issues/506. Still blocked.

**Comment by karntrehan** [comment]
Ingestion to be picked up today by @Ajay-Maury

**Comment by karntrehan** [comment]
Awaiting data from PT in correct format.

**Comment by karntrehan** [comment]
Data received. Data ingested on staging. 1 district pending. When received we shall ingest.

**Comment by karntrehan** [comment]
Fusion auth activation and deactivation added.

**Comment by AakashSatpute119** [comment]
Deactivate examiner getting something went wrong and unable to log in![Image](https://github.com/user-attachments/assets/1f36cb91-c0f0-4e82-aa2c-bf3670ee4aa6)
![Image](https://github.com/user-attachments/assets/8f8b327e-5ab3-44de-bb43-5322c98d7ceb)
.

**Comment by VargishChauhan** [comment]
Checking the invalid message

**Comment by karntrehan** [comment]
@AakashSatpute119 to test.

**Comment by karntrehan** [comment]
Message on frontend to be updated - @charanpreet-s . Content to be: 
```
This mobile number is not registered.\nTo register on Prerna portal, please call the DC Training/Quality in BSA office or call helpline number.
```

**Comment by karntrehan** [comment]
Error message to be picked from BE. FE change not showing up. @charanpreet-s to debug.

**Comment by dhruv-1001** [comment]
Build shared and tested by @AakashSatpute119.
