### ISSUE TITLE
(Examiner) 1680 Sets ingestion

### ISSUE THREAD

**Issue by VargishChauhan** [Mission-Prerna/nl-apis#263]
Need to ingested the Examiner question for assessment.

- [ ] Receive data from PT
- [ ] Validate Data
- [ ] Ingest data to staging
- [ ]  Test on staging
- [ ] Ingest data to PROD 
- [ ] Test on PROD

**Comment by VargishChauhan** [comment]
Hi,
PT has shared 1280 set in the below Excel. 

[Link](https://docs.google.com/spreadsheets/d/1aZaHOnMRI6Ymk39gYciWq1Wj6uAaA1IfzUBd1ZNtIs4/edit?gid=674844113#gid=674844113) 

They will be sharing the remaining by end of this week.

**Comment by VargishChauhan** [comment]
@AakashSatpute119  Please verify the questions mapped 
[Link](https://docs.google.com/spreadsheets/d/1aZaHOnMRI6Ymk39gYciWq1Wj6uAaA1IfzUBd1ZNtIs4/edit?gid=674844113#gid=674844113)

are tagged to the correct competencies for examiner

**Comment by VargishChauhan** [comment]
We will ingest for now. mapping and testing will happen when we receive all sets

**Comment by charanpreet-s** [comment]
@VargishChauhan to discuss with @Ajay-Maury for data related issues

**Comment by dhruv-1001** [comment]
@dhruv-1001 to update competency data on prod.

**Comment by VargishChauhan** [comment]
Deprioritizing for now. Will be taken next week

**Comment by karntrehan** [comment]
1200 sets recived. Verified and ingested to staging.
Prod competencies to be updated on prod. 
Awaiting data from PT.

**Comment by karntrehan** [comment]
Linked to https://github.com/Mission-Prerna/prerna-lakshya-app/issues/506. Still blocked.
