### ISSUE TITLE
Real-time SOS data integration to VSK

### ISSUE THREAD

**Issue by VargishChauhan** [Mission-Prerna/nl-apis#264]
NL app need to send SOS data captured through our app to VSK screen.

**Comment by dhruv-1001** [comment]
@VargishChauhan to co-ordinate with PT for call with VSK.

**Comment by AakashSatpute119** [comment]
- PT to check data in `school_results_fraud_reports` this table.
- Get clarity from PT on notify reports.

**Comment by VargishChauhan** [comment]
Doesn't require any development effort for this ticket
