### ISSUE TITLE
CWSN student exclusion from examiner list

### ISSUE THREAD

**Issue by VargishChauhan** [Mission-Prerna/nl-apis#265]
Children with special needs should be excluded from examiner assessment . But teacher assessment and mentor should work

- [x] PT to provide list of CWSN student with student ID's
- [ ] Tech scoping
- [ ] Build API
- [ ] Ingest data on staging
- [ ] Test on staging
- [ ] Deploy to prod
- [ ] Ingest data on staging
- [ ] Test on prod

**Comment by karntrehan** [comment]
Linked to https://github.com/Mission-Prerna/prerna-lakshya-app/issues/506. Still blocked.

**Comment by karntrehan** [comment]
Deprioritised to 2422.

**Comment by karntrehan** [comment]
### Tech scope: 

- [ ] Create a table for CWSN (children_with_special_needs). Structure: udise, student_id, is_active, created, updated
- [ ] Pull data from CSV shared by PT into the table. Ignore additional PII columns.
- [ ] While creating cycle, update query to: select * from students where school_id = X and student not in children_with_special_needs

**Comment by karntrehan** [comment]
Data received contains 2K users that are not in our database. Unique ID is sometimes string. We will ignore the same and go ahead with ingestion onto production.

**Comment by Ajay-Maury** [comment]
PR:- https://github.com/Mission-Prerna/nl-apis/pull/315

**Comment by VargishChauhan** [comment]
Completed
