### ISSUE TITLE
[Documentation] Document the examiner cycle management process

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#270]
We should document the entire cycle management process: 

- [x] 1. Invalidating existing examiners
- [x] 2. Adding examiners
- [ ] 3. Creating cycle - Data required
- [ ] 4. Randomizer setup
- [ ] 5. Testing cycle setup

**Comment by Ajay-Maury** [comment]
Added script and docs which contains:- 
-  Parsing and validating CSV file
- Invalidating existing examiners
-  Creating new examiners from CSV data
- Mapping them to the latest assessment cycle
-  Logging errors

**Comment by charanpreet-s** [comment]
@Ajay-Maury dependent on data from PM for the cycle

**Comment by charanpreet-s** [comment]
@Ajay-Maury to add curl for the api for reset schools-cycle mapping

**Comment by charanpreet-s** [comment]
@Ajay-Maury to add user journey diagram

**Comment by karntrehan** [comment]
Biblography added. 
User flow diagram pending. @karntrehan to take a crack at this for now.

**Comment by karntrehan** [comment]
Raw: https://drive.google.com/file/d/1dtlBK7rctww31NjxS-uVg22gYxNnenax/view?usp=sharing

![Image](https://github.com/user-attachments/assets/f87633b5-a986-47e6-8514-2ab153ea82fd)

**Comment by karntrehan** [comment]
v2 of diagram: 


![Image](https://github.com/user-attachments/assets/e3f3745a-ef67-4879-bd99-928f138c2879)

**Comment by VargishChauhan** [comment]
Completed the document.
