### ISSUE TITLE
Re-ingesting question with correct option

### ISSUE THREAD

**Issue by VargishChauhan** [Mission-Prerna/nl-apis#271]
There have been problem identified where the students are giving answers which are not covered in the option list of the Reading comprehension
PT team has added/ modified option to accommodate the scenario in the option list. We need to re - ingest the questions/ set which have been modified

**Comment by AakashSatpute119** [comment]
- Get update from snehi @VargishChauhan

**Comment by VargishChauhan** [comment]
Hi @AakashSatpute119 ,
[Link](https://docs.google.com/spreadsheets/d/1E0odarfEsb-uioJpzKPQPm0SGuaU1jDFLAEGtF_LFGw/edit?gid=0#gid=0)  list of question for re-ingestion . 

cc @karntrehan @charanpreet-s

**Comment by AakashSatpute119** [comment]
> Hi [@AakashSatpute119](https://github.com/AakashSatpute119) , [Link](https://docs.google.com/spreadsheets/d/1E0odarfEsb-uioJpzKPQPm0SGuaU1jDFLAEGtF_LFGw/edit?gid=0#gid=0) list of question for re-ingestion .
> 
> cc [@karntrehan](https://github.com/karntrehan) [@charanpreet-s](https://github.com/charanpreet-s)

@Ajay-Maury  please check format.

**Comment by dhruv-1001** [comment]
Ingestion & testing done on staging.
To be ingested on prod.
@Ajay-Maury to update script for prod.

**Comment by AakashSatpute119** [comment]
Reingested on prod  and tested- 
**Hindi Grade: 3 -** 
``` `"PYWlr3Cfc9e1",
 "Egw1beOlSMm4",
 "tYe7358OhNqk", 
"lfvOEQRyCEIo" ````

**Hindi Grade : 2 -** 
````"Iml8au5BDu0P",
 "6McmTqTeNcOA",
 "CEZKMkhcLNgv",
 "w43gb3b8XlvS",
 "hXCZIZg9Ig83", 
"1PF5UE7CJTHm",
 "xiFEg5DPRgrC"````
