### ISSUE TITLE
RCT - Remove dashboard data

### ISSUE THREAD

**Issue by VargishChauhan** [Mission-Prerna/nl-apis#273]
For the schools which are blocked, Assessment data that is shown on the dashboard should not be shown. It can be shown zero or kept blank

![Image](https://github.com/user-attachments/assets/463cef7a-cfe0-4eed-9c29-b7ab413b1cc8)

**Comment by dhruv-1001** [comment]
@TheNPDev to share build for testing.

**Comment by karntrehan** [comment]
Release Getting tracked in https://github.com/Mission-Prerna/prerna-lakshya-app/issues/496
