### ISSUE TITLE
Posthog Migration to Govt Server

### ISSUE THREAD

**Issue by nikhil241** [Mission-Prerna/nl-apis#280]
Related to this ticket
https://github.com/orgs/Mission-Prerna/projects/2/views/1?pane=issue&itemId=69457195

**Comment by karntrehan** [comment]
Picked today.
Backup started. Prod Downtime: ~4 hours. To be done in the second half today.

**Comment by karntrehan** [comment]
Deployment not completed yesterday due to @karntrehan's absence. 

Deployment plan:
Currently nl.telemetry.X.X maps to our server and is configured through remote config to all users. 

We shall create a new domain -> nipun.telemetry.X.X mapping to the govt server (103.X.X.X) and test first on staging, followed by phased rollout of the domain to all users. 

cc @nikhil241

**Comment by VargishChauhan** [comment]
Nikhil and Ajay are working on it.

**Comment by AakashSatpute119** [comment]
- @TheNPDev  to share new build for testing.

**Comment by TheNPDev** [comment]
@AakashSatpute119 
Build: https://drive.google.com/file/d/1qbZYlzXpLj1Y6KiIif8hkjbLQTBpAfs9/view?usp=sharing

**Comment by charanpreet-s** [comment]
@dhruv-1001 to add posthog creds to creds sheet

**Comment by dhruv-1001** [comment]
@AakashSatpute119 to connect with @nikhil241 to check out why it's not getting events.

**Comment by AakashSatpute119** [comment]
Able to see events on new PostHog server. @nikhil241

**Comment by charanpreet-s** [comment]
@nikhil241 is migrating data. Post that android URLs will be changed on firebase.

**Comment by dhruv-1001** [comment]
@charanpreet-s to point to new telemetry URL.

**Comment by charanpreet-s** [comment]
Moving to 10% of the users

**Comment by karntrehan** [comment]
Experiment config did not work. Only 3 events in an hour received. @charanpreet-s to fix 10% rollout. Post that call to be taken. 

Data will needed to be migrated. To be done next week.

**Comment by VargishChauhan** [comment]
New Events not getting captured on govt servers.
Need to do an RCT for the same

**Comment by karntrehan** [comment]
Clickhouse and zookeeper have gone out of sync. @nikhil241 to check by redeploying older backup. Once system is up and running, we can test internally. All users to keep pointing to nl.X.X.X. 

On the weekend, nl.X.X.X to be put down. Entire data to be migrated to nipun.X.X.X. Tested quickly and on monday all users to point to nipun.X.X.X from firebase. 

cc @nikhil241 @charanpreet-s @AakashSatpute119

**Comment by dhruv-1001** [comment]
@AakashSatpute119 to test again.

**Comment by AakashSatpute119** [comment]
> [@AakashSatpute119](https://github.com/AakashSatpute119) to test again. [@nikhil241](https://github.com/nikhil241) to take backup during weekend.

Tested with this [Build](https://drive.google.com/file/d/1qbZYlzXpLj1Y6KiIif8hkjbLQTBpAfs9/view?usp=sharing) getting all events on a new server.

**Comment by VargishChauhan** [comment]
Migration to govt server complete.
