### ISSUE TITLE
[Documentation] Document the assessment data API

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#281]
- [x] Document the assessment API
- [x] Define all parameters
- [x] Add a video
- [x] (Optional) Limit delta of days in the API

**Comment by Ajay-Maury** [comment]
Demo video:- https://drive.google.com/file/d/1wKi8OOkRJxUbZC58uI1VmUQbiEBDadQH/view?usp=sharing

**Comment by charanpreet-s** [comment]
@karntrehan  to review PR

**Comment by VargishChauhan** [comment]
PR review pending. Ready for testing

**Comment by VargishChauhan** [comment]
Will be closed today.

**Comment by karntrehan** [comment]
Followup: [#284](https://github.com/Mission-Prerna/nl-apis/issues/284)

**Comment by AakashSatpute119** [comment]
- @Ajay-Maury  to update and merge PR
- Create separate ticket
