### ISSUE TITLE
[Ad Hoc] Remove duplicate blocks and districts

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#282]
We currently have duplicate blocks and districts where one of them is lowercase and one is uppercase. We should check if we can drop the lowercase elements. 

- [x] Identify lowercase and uppercase districts + blocks
- [ ] Identify mentors mapped to lowercase d+b
- [ ] Identify mentor anomalies in mapping.

**Comment by Ajay-Maury** [comment]
Districts with their mapped `block`, `mentor`, `school_list`, and `nyay_panchayats`:- 

staging:- [stag-districts.zip](https://github.com/user-attachments/files/16599846/stag-districts.zip)

prod:- [prod-districts.zip](https://github.com/user-attachments/files/16599853/prod-districts.zip)

**Comment by karntrehan** [comment]
Mappings created between duplicates. Call to be taken. @Ajay-Maury to setup call with @karntrehan and @VargishChauhan.

**Comment by VargishChauhan** [comment]
We will make the changes for NISAI. Closing this ticket and will open another for that
