### ISSUE TITLE
[BE] Audit Prod Storage

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#287]
We have used 5TB storage space on prod. We need to audit what service is hogging up so much memory and archive some data.

**Comment by dhruv-1001** [comment]
@nikhil241 to delete migration backup files files.

**Comment by karntrehan** [comment]
Backup files deleted by @nikhil241. 5.3TB being used. @Ajay-Maury and @nikhil241 to connect today to analyse this further. 

Break of what is using how much space -> App DB, Posthog, UCI, etc..

**Comment by karntrehan** [comment]
## Current storage pattern: 

335G    NL-old
363G    nl-tsdb-backups
577G    posthog-data
110M    posthog-deploy
286G    timescaledb-new
272G    timescaledb
114G    uci-services
36G     backups
273G    nl-tsdb-17thjan-backup

docker-lib ->

329G    containers
2.6T    volumes
598M    image
283G    overlay2


## AIs: 

- [ ] 1.5 TB logs of postgres (`home/remote/docker-lib/volumes/hasura_tdb-data/_data/log`) to be cleared. Log rotation of 10 days to be added - @Ajay-Maury 
- [ ]

**Comment by dhruv-1001** [comment]
@dhruv-1001 @karntrehan @Ajay-Maury to connect on tsdb.

**Comment by dhruv-1001** [comment]
@dhruv-1001 @Ajay-Maury to audit and remove duplicate tables. And list out learnings.

**Comment by TheNPDev** [comment]
third point cannot be deleted

**Comment by chinmoy12c** [comment]
## UCI Disk Space Utilization Analysis (WIP)

- Total Folder Space - 97 GB
  - Stale Backup (`data-backup`) - 46 GB
    - Growth Rate - Stagnant 
    - Last Modified - Feb 15
    - Can be deleted
  - Stateful Data (Databases) - 52 GB
    - Growth Rate - Not Exponential
    - Last Modified - Live Modification (stores db data)
   - Stateless Services - 115 MB
     - Growth Rate - Stagnant
     - Last Modified - Whenever new services need to be deployed

**Comment by karntrehan** [comment]
WIP. To be closed by 3rd.

**Comment by nikhil241** [comment]
To clean up logs in PostgreSQL, we need to write a script and schedule it using a cron job.

**Comment by dhruv-1001** [comment]
Actions items to be planned on 3rd.
- [ ] Mounting docker volumes to specific folder.
- [ ] To clean up logs in PostgreSQL, through script.

**Comment by dhruv-1001** [comment]
@chinmoy12c to list out what all can be deleted.
@chinmoy12c @nikhil241 to connect on cron. Need to delete NL & UCI logs.

**Comment by nikhil241** [comment]
A cron job has been set up for Postgres logs for the time being.

**Comment by dhruv-1001** [comment]
## Current storage pattern: 

### Total size: 7.0TB
### Occupied size: 2.9TB
### Size left: 3.8TB
### Time left: 9 - 15 months

**Comment by karntrehan** [comment]
- UCI cleanups to be added to cron. 

Can be closed post addition.
