### ISSUE TITLE
Add monitoring and alerting on pgbouncer and other services

### ISSUE THREAD

**Issue by Ajay-Maury** [Mission-Prerna/nl-apis#290]
Need to add monitoring and alerting on pgbouncer and other services in NL.

**Comment by Ajay-Maury** [comment]
- [ ] Monitoring added in grafana (already exists)
- [ ] Added uptime kuma alerts

**Comment by karntrehan** [comment]
Done and merged. Grafana already existed. Uptime Kuma integrated now.
