### ISSUE TITLE
[Bug] Posthog loading time

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#296]
Posthog dashboard is loading very slowly. Need to debug the performance hit.

**Comment by dhruv-1001** [comment]
@nikhil241 to pick this up today.

**Comment by VargishChauhan** [comment]
In progress

**Comment by karntrehan** [comment]
Working well now. @VargishChauhan to check.

**Comment by AakashSatpute119** [comment]
- postHog is working fine now.

**Comment by karntrehan** [comment]
Loading time is still slow. Settings to be re-applied which were lost after a restart. Permanency of the settings to be figured.

**Comment by karntrehan** [comment]
Steps taken on prod server: 

1. Cache of posthog increased from 2GB to 4GB in redis.
2. Threads (Django) from 32 to 64.
3. Load on CPU is almost the same. 

Working fine. Closing.
