### ISSUE TITLE
[QA] Testing student APIs

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#31]
Plan and implement the automation tests for the newly created APIs for teacher <> student data.

**Comment by karntrehan** [comment]
Blocked as bandwidth is being consumed by Samarth.

**Comment by Nirali010129** [comment]
https://drive.google.com/file/d/1Mvo0PY4YsF2OyuarfO8jEN5d1s6_8ZYo/view?usp=drive_link 

Please review @AakashSatpute119 


cc : @karntrehan @aakashyadav-kgp
