### ISSUE TITLE
[TECHNOSYS] Getting student data API from technosys via delta query support

### ISSUE THREAD

**Issue by choxx** [Mission-Prerna/nl-apis#33]
We shall ask Technosys to provide us with an API to feed the data into NL DB.

**Comment by choxx** [comment]
## API Contract

### `GET https://example.com/api/students`
It should be a GET API. The host URL & path are just for reference. It could be anything at your convenience.

### Query Params
- `last_modified_at`: A date-time string in either ISO format or Unix timestamp. With this query param passed, API should respond with all the student records created or modified after this timestamp.
- `page`: pagination parameter to tell which page it is.
- `perPage`: the max number of records that should be available in that particular API call

### Response
The API should respond with all the below mentioned details:
1. Total Pages
2. Current Page
3. Total Records count
4. Items (student records)

Sharing a sample response below:
```
{
  "pages": 100,
  "page": 1,
  "total": 1000,
  "items": [
    {
      "name": "Student 1",
      "gender": "male", // or "female"
      "dob": "2001-12-21",
      "addmission_date": "2006-04-10",
      "roll_no": 1234,
      "unique_id": "xxxx",
      "father_name": "Mr. X",
      "mother_name": "Mrs. Y",
      "grade": 1,   // must be a numeric digint b/w 1-12
      "section": "A",   // if any; otherwise empty string
      "udise": 90112091211  // School's Udise
    },
    ... // other records
  ]
}
```

**Comment by karntrehan** [comment]
Technosys is going to give us a dump of data and not an API. 

Get CSV from Technosys segregated by block. @choxx to share the format of CSV we need.

**Comment by choxx** [comment]
@aakashyadav-kgp 

[Sample CSV for Students.ods](https://github.com/Mission-Prerna/nl-apis/files/12453946/Sample.CSV.for.Students.ods)

**Comment by aakashyadav-kgp** [comment]
Details shared with technosys with format

**Comment by karntrehan** [comment]
ETA: 6th September

**Comment by karntrehan** [comment]
Data received as CSV. Tab separated data received with some data in different format. Will be processed and inserted by @yuvrajsab  in #34 .
