### ISSUE TITLE
[BE] Pulling one time student data into db

### ISSUE THREAD

**Issue by choxx** [Mission-Prerna/nl-apis#34]
Initial syncing of all 1cr student records to NL DB.

**Comment by choxx** [comment]
To be picked after #33 is ready

**Comment by karntrehan** [comment]
As #33 is closed, @yuvrajsab to start on this today.

**Comment by yuvrajsab** [comment]
CSV data is in an inconsistent format  (wrongly tab formatted)

**Comment by karntrehan** [comment]
@yuvrajsab to process and insert valid data. Incorrect and invalid data to be flagged and shared with technosys to fix. Additional efforts on script are understandable.

**Comment by charanpreet-s** [comment]
@aakashyadav-kgp to share the feedbacks to technosys

**Comment by karntrehan** [comment]
Dumped all data to staging. To be migrated to prod simply with a backup.
