### ISSUE TITLE
[BE] Architect system APIs to process and return student records for teachers

### ISSUE THREAD

**Issue by choxx** [Mission-Prerna/nl-apis#36]
Design system architecture for various APIs needed in the new flow.

https://www.figma.com/file/KEv3Bga4hygJiw4QPFMxx3/NL-App_May_2023?type=design&node-id=1030-1996&mode=design

**Comment by choxx** [comment]
API Contract: https://github.com/Mission-Prerna/prerna-lakshya-app/issues/266

**Comment by karntrehan** [comment]
Awaiting tables and data.

**Comment by charanpreet-s** [comment]
@choxx to deploy this on a temp branch

**Comment by ujjwalsaxena03** [comment]
@choxx to raise a PR shortly.

**Comment by choxx** [comment]
PR raised: https://github.com/Mission-Prerna/nl-apis/pull/48

**Comment by aakashyadav-kgp** [comment]
@ChakshuGautam please review the PR.

**Comment by karntrehan** [comment]
@Nirali010129 to write API tests post closure of samarth tickets.

**Comment by karntrehan** [comment]
Awaiting PR review from @ChakshuGautam

**Comment by karntrehan** [comment]
Feedback received. Fixes undertaken. Ticket to be tested with android.
