### ISSUE TITLE
[BE] Save Assessment Results coming from the frontend for each student

### ISSUE THREAD

**Issue by choxx** [Mission-Prerna/nl-apis#37]
- API for assessment results submission against student(s).
- [Student Assessment history](https://github.com/Mission-Prerna/prerna-lakshya-app/issues/266#issuecomment-1692923984)
- [School Performance](https://github.com/Mission-Prerna/prerna-lakshya-app/issues/266#issuecomment-1693293142)
- [Teacher Performance](https://github.com/Mission-Prerna/prerna-lakshya-app/issues/266#issuecomment-1693295920)

**Comment by charanpreet-s** [comment]
@choxx Sumissions API to get closed today, and will continue with others

**Comment by ujjwalsaxena03** [comment]
Dev closed. @choxx will raise a PR.

**Comment by choxx** [comment]
PR raised: https://github.com/Mission-Prerna/nl-apis/pull/48
