### ISSUE TITLE
[ANALYTICS] Define structure for visualisation

### ISSUE THREAD

**Issue by choxx** [Mission-Prerna/nl-apis#39]

**Comment by choxx** [comment]
- [ ] In the existing MV `assessment_result_nl_dashboard`, we'll add an additional column named `student_id` & accommodate the changes in the query. @choxx 
- [ ] New visualizations for the new teacher <> students flow will be added on Metabase for visualizations. @aakashyadav-kgp

**Comment by choxx** [comment]
To be picked post #53 migration to single table structure.

**Comment by choxx** [comment]
Resuming this as #53 p1 is done.

**Comment by choxx** [comment]
@aakashyadav-kgp @Sanyem 
- I've added a new MV for teacher <> students flow. 
- The existing MV has been fixed to use a single `assessments` hyper table going forward. Please test the Metabase if there is any misalignment in the visualizations.

**Comment by choxx** [comment]
@choxx to clear the records for future dates; causing Metabase visualization breaking.

**Comment by choxx** [comment]
Done. @Sanyem please verify

**Comment by Sanyem** [comment]
Working fine, thanks. Moving to Done
