### ISSUE TITLE
NL App Data exposure

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#55]
1. Teacher logins. 
2. Chatbot telemetry.

**Comment by karntrehan** [comment]
Questions: 

Login
1. How would the external system map NL mentor IDs to actual mentors? - Phonenumber? Name? etc?  - @aakashyadav-kgp @Sanyem 
2. Teacher logins - Overlap of Hasura + Posthog events (post v2)  - @aakashyadav-kgp @Sanyem 
3. Should we implement force logout in v2.  - @aakashyadav-kgp @Sanyem 

Chatbot TL
1. How would the external system map NL mentor IDs to actual mentors? - Phonenumber? Name? etc? - @aakashyadav-kgp @Sanyem 
2. Events to expose (mentor_id): When user clicks chat fab, When user opens specific bot (bot id).

**Comment by choxx** [comment]
## Questions
1. Can we do a force update with v2? This would ensure we don't have to overlap the login data b/w Hasura & Posthog everytime, and the single source of truth will be Posthog
2. Can we think of directly exposing the data via Posthog APIs?
3. Can we think of exposing the visualized data via Metabase APIs? (some R&D is needed in this front)

**Comment by aakashyadav-kgp** [comment]
To be picked from tom second half

**Comment by Sanyem** [comment]
Use Case for Login API: Need data for users who have logged in atleast once. Need to do a union on posthog data + pin from postgres. 

Format needed: {phone_no, user_type (teacher, examiner, mentor), district_name, block_name (Applicable for teachers and mentors), udise_code (applicable for teachers)}

Use case for Chatbot usage API: Need to filter these events: 'nl-chatbotscreen-notification-opened', 'nl-chatbotscreen-chatbot-interactions','nl-assessmenttypeselection-chatbot-initiate'

Format needed: {phone_no, user_type (teacher, examiner, mentor), district_name, block_name (Applicable for teachers and mentors), date, # of views/usage}

Use case for student wise assessment: Need data for student wise assessments so NBMC can collate and do visualisations. 

Format needed: {assessment_id, phone_no, student_roll_no (unique_id), class, user_type (teacher, examiner, mentor), district_name, block_name (Applicable for teachers and mentors), udise, date_of_assessment, result (NIPUN/NOT NIPUN/INCOMPLETE if possible)}

**Comment by ujjwalsaxena03** [comment]
Issue raised with Hasura. wait for them to come back with an ETA. Also, discuss us contributing to Hasura.
Clickhouse becomes our source of truth.

**Comment by charanpreet-s** [comment]
@tushar5526 to provide ETA on manual API creation

**Comment by tushar5526** [comment]
The approach to this is finalised. 

2 tables `teacher_school_mapping` and `school_list`will be synced with clickhouse to share the requested data. All APIs will be created on the `nl-datalake` repo using basic auth.

**Comment by choxx** [comment]
As Hasura data connectors for Clickhouse hasn't been working out for us, we wrote custom APIs in flask. 
The curls have been shared with @Sanyem to verify.

**Comment by tushar5526** [comment]
Deployed to prod, all 3 curls shared in postman with Sanyem and changed the authentication from hard-coded secret to Fusion Auth-based JWT tokens.
