### ISSUE TITLE
[BE] Cycle, District & school, Examiner Mapping APIs

### ISSUE THREAD

**Issue by choxx** [Mission-Prerna/nl-apis#59]
API Contract: #58 

- [x] 1. **Cycles API:** This will take in start_date, end_date, class 1 student count, class 2 student count, class 3 student count and nipun_percentage. Student count will remain same for the whole cycle
- [x] 2. **Disctrict <> Schools mapping API:** This will take CSV input to map districts to nominated schools. The CSV will take in district_id and school_id.
- [x] 3. **Examiner <> District <> Cycle mapping API:** The API takes a CSV as input. The CSV has user_id of examiner, district id, cycle_id. An examiner can be assigned to more than 1 district
- [x] 4. **Invalidate Assessments API:** This would take on user_id, UDISE, cycle_id and param to delete just the results or the whole assessment mapping to the user of that school.

**Comment by choxx** [comment]
1) API closed on Friday. Rest to be closed today.

**Comment by choxx** [comment]
Considerations for the APIs:
1. Direct CSV upload support isn't available easily at the backend. So, the suggested approach is:
  1.1. Create a CSV
  1.2. Use any online tool to convert the CSV into JSON e.g. https://csvjson.com/csv2json and pass the JSON input to the API 2) & 3).
2. Considering the backend validations & the random students mapping to be generated for **Disctrict <> Schools mapping API**, there a request **limit to create max 1000** mapping in a single API call.
3. Considering the backend validations & the random students mapping to be generated for **Examiner <> District <> Cycle mapping API**, there a request **limit to create max 5000** mapping in a single API call.

**Comment by Sanyem** [comment]
1. csv to json can be done
2. @Sanyem to get an estimate of scale from PT
3. @Sanyem to get an estimate of scale from PT

**Comment by choxx** [comment]
All APIs are ready & deployed on staging. Sharing sample curls below:
## Create Cycle
```
curl --location 'localhost:3000/admin/assessment-cycle' \
--header 'Authorization: Bearer {{token-here}}' \
--header 'Content-Type: application/json' \
--data '{
    "name": "Cycle (1 Nov - 30 Nov)",
    "start_date": "2023-11-01",
    "end_date": "2023-11-30",
    "class_1_students_count": 5,
    "class_2_students_count": 9,
    "class_3_students_count": -1,
    "nipun_percentage": 75
}'
```

## Create Disctrict <> Schools mapping
```
curl --location 'localhost:3000/admin/assessment-cycle/1/district-school-mapping' \
--header 'Authorization: Bearer {{token-here}}' \
--header 'Content-Type: application/json' \
--data '[
  {
    "district_id": 42,
    "udise": 9530507604
  },
  {
    "district_id": 97,
    "udise": 9260202302
  }
]'
```

## Examiner <> District <> Cycle mapping
```
curl --location 'localhost:3000/admin/assessment-cycle/4/district-examiner-mapping' \
--header 'Authorization: Bearer {{token-here}}' \
--header 'Content-Type: application/json' \
--data '[
    {
        "mentor_id": 33007,
        "district_id": 34
    }
]'
```

## Invalidate Assessments
```
curl --location 'localhost:3000/admin/assessment-cycle/4/invalidate-examiner-assessments' \
--header 'Authorization: Bearer {{token-here}}' \
--header 'Content-Type: application/json' \
--data '{
    "mentor_id": 375874,
    "udises": [0],
    "delete_all": true
}'
```
