### ISSUE TITLE
[BE] District ID not required in school <> cycle mapping. 

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#66]
#59 has an unnecessary school district mapping. District should be taken from school list and it should be source of truth.

**Comment by tushar5526** [comment]
PR raised, to be reviewed by @choxx

**Comment by tushar5526** [comment]
Deployed on dev @AakashSatpute119 

Flows to be tested

- [ ] getExaminerHomeScreenMetric
- [ ] getSchoolStatus
- [ ] getExaminerCycleDetails
- [ ] createAssessmentCycleDistrictSchoolMapping

**Comment by ujjwalsaxena03** [comment]
To be tested by @AakashSatpute119

**Comment by AakashSatpute119** [comment]
After submitting the school assessment successfully through the app , **assessment_cycle_school_nipun_results** table is not updated unable to see any submission due to this 1.examiner stats.
2.school nipun status.
are affected. 

![Image](https://github.com/Mission-Prerna/nl-apis/assets/132545585/083cc4ce-a916-4ee2-bf3a-e96014a826b2)

**Comment by charanpreet-s** [comment]
@tushar5526 to verify the API with @choxx

**Comment by tushar5526** [comment]
Fix merged and deployed. To be tested by @AakashSatpute119 again.

**Comment by AakashSatpute119** [comment]
School result calculate API calculating the wrong status, 
9670606001  school should nipun as per the cycle configured. 
https://prnt.sc/cNZCGTr1f1Sm 
Cycle Id : 10 
Mentor id : 375857 
UDISE : 9670606001 

Cycle Details : https://prnt.sc/gEBvsjIgIbZf  
https://screenpal.com/watch/c0XQXqVGoJy

**Comment by choxx** [comment]
It's fixed @AakashSatpute119

**Comment by Sanyem** [comment]
Prod Testing to be done

**Comment by Sanyem** [comment]
Unique constraint to be added in school mapping to avoid adding same udise code multiple times
