### ISSUE TITLE
Mentor's schools list & if he has visited

### ISSUE THREAD

**Issue by choxx** [Mission-Prerna/nl-apis#7]
## Request
- GET `/api/mentor/schools?month=3&year=2023`
The API will return the list of allocated schools to the logged in mentor based on his District/Block mapped to him.
(`month` & `year` are optional; if not passed, present day's values will be picked)

## Response
```json
{
  "items": [
    {
        "id": 1,
        "udise": 90000000,
        "is_visited": true,
        ...
    }
  ]
}
```

**Comment by shashankluezoid** [comment]
@choxx Please add given keys in response-
schoolName
district
block
nyayPanchayat
