### ISSUE TITLE
[BE] Share API docs

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#71]
Share all API documents in a single repo.

**Comment by karntrehan** [comment]
Explore either continuing with Postman or moving to Bruno.

**Comment by charanpreet-s** [comment]
API repo created.

**Comment by tushar5526** [comment]
Learnings sheet 
https://docs.google.com/spreadsheets/d/1Q0r9GAIYIplQVohdmTb0Zv5zX5sLTOQURPuU8OYFtQI/edit#gid=0

**Comment by rohitsamagra** [comment]
- Going ahead with Postman and not Bruno
- To figure out collaboration with Postman (Karan to discuss with Tushar)

**Comment by karntrehan** [comment]
Bruno would not work for us as we need to share APIs externally with vendors. We should be using Postman with Exporting and importing collections and adding those to our git repos. 

https://learning.postman.com/docs/getting-started/importing-and-exporting/exporting-data/#exporting-data-dumps
https://www.npmjs.com/package/newman#command-line-options

**Comment by rohitsamagra** [comment]
Discuss how to use in a seperate ticket
