### ISSUE TITLE
[P0][Bug] Handle unique id preceding 0 and roll number constraint in student insertion

### ISSUE THREAD

**Issue by karntrehan** [Mission-Prerna/nl-apis#87]
![Image](https://github.com/Mission-Prerna/nl-apis/assets/5885669/6c23ea77-1333-4fd8-9e00-6f25bc93743c)

Some teachers seeing duplicate students. To be fixed. 

New students might have assessment mapped to them, we should find the count and delete if it is small. If it is large, we should migrate to older student data (if possible).

**Comment by Sanyem** [comment]
Now that we have a proper assessments cycle with cycle_id 6. We will have to check first which unique ID is used in the assessment. cc @karntrehan

**Comment by karntrehan** [comment]
POA: 

1. Find wrong students - (1(newer) vs 01 (older))
2. Update wrong students from cycle mapping. Edge case - when low number of students both right and wrong will be in the list. Delete wrong students.
3. Update assessment results from wrong to right. Delete if duplicates. 
4. Delete wrong students (1(newer))

**Comment by rohitsamagra** [comment]
To be re-run today and check out for edge cases

**Comment by rohitsamagra** [comment]
To be updated in one table(students), to be done today

**Comment by rohitsamagra** [comment]
Fixed
