### ISSUE TITLE
Fix the "calculate school result" logic at backend.

### ISSUE THREAD

**Issue by tushar5526** [Mission-Prerna/nl-apis#98]
A school would be considered nipun only when all the 3 classes are nipun. A class would be considered nipun only when 75% (pulled from cycle config) of the students from the randomiser have been assessed as nipun. 

Ex: If the randomiser has picked 12 students for class 1 of a school and 6 are marked as absent by the examiner, the class becomes not nipun and the school too becomes not nipun. All 3 classes need atleast 9 nipuns for the school to be treated as nipun. If the randomiser has picked 9 students for class 1, atleast 7 students should be nipun, else class and school is not nipun.

**Comment by rohitsamagra** [comment]
A school would be considered nipun only when all the 3 classes are nipun. A class would be considered nipun only when 75% (pulled from cycle config) of the students from the randomiser have been assessed as nipun. 

Ex: If the randomiser has picked 12 students for class 1 of a school and 6 are marked as absent by the examiner, the class becomes not nipun and the school too becomes not nipun. All 3 classes need atleast 9 nipuns for the school to be treated as nipun. If the randomiser has picked 9

**Comment by tushar5526** [comment]
Query currently being used. Students are getting grouped properly per class. The only fault is in the logic where only one assessment is being considered for `is_passed` instead of all assessments. 
```sql
select
	grade,
	(
                  case
		when t.grade = 1 then (count(t.student_id) * 100) / 5
		when t.grade = 2 then (count(t.student_id) * 100) / 5
		when t.grade = 3 then (count(t.student_id) * 100) / 5
		else 0
	end
                  )::int as percentage,
	 	(
	  case
		when t.grade = 1 then count(t.student_id)
		when t.grade = 2 then count(t.student_id)
		when t.grade = 3 then count(t.student_id)
		else 0
	end
                  )::int as percentage
from
	(
	select
		distinct on (a.student_id)
		student_id,
		a.is_passed,
		a.grade,
		a.assessment_type_id ,
		a.competency_id,
		a.id
	from
		assessments a
	where
		a.student_id in (
                                    '037611849', '037611058', 
                                    '037614771', '039939331', '037616222', 
                                    '383259882', '216236386', '383460874', 
                                    '413878162', '383322690', '206928879', '306093898', 
                                    '358693278', '236807970', '291352705'
                 )
		and udise = 9150206703
		and grade in (1, 2, 3)
		and mentor_id = 375857
		and a.submitted_at between '2023-12-08' and '2023-12-30'
		order by a.student_id , a.id 
		) t
where
	t.is_passed = true
group by
	t.grade
```

Fixed Query

```sql
select
	grade,
	(
                  case
		when t.grade = 1 then (count(t.student_id) * 100) / 5
		when t.grade = 2 then (count(t.student_id) * 100) / 5
		when t.grade = 3 then (count(t.student_id) * 100) / 5
		else 0
	end
                  )::int as percentage,
	 	(
	  case
		when t.grade = 1 then count(t.student_id)
		when t.grade = 2 then count(t.student_id)
		when t.grade = 3 then count(t.student_id)
		else 0
	end
                  )::int as passed
from
	(
	select
		student_id,
		a.grade,
                -- check all rows for the student's assessment should be true
		bool_and(a.is_passed) is_passed
	from
		assessments a
	where
		a.student_id in (
                                    '037611849', '037611058', 
                                    '037614771', '039939331', '037616222', 
                                    '383259882', '216236386', '383460874', 
                                    '413878162', '383322690', '206928879', '306093898', 
                                    '358693278', '236807970', '291352705'
                 )
		and udise = 9150206703
		and grade in (1, 2, 3)
		and mentor_id = 375857
		and a.submitted_at between '2023-12-08' and '2023-12-30'
		group by a.student_id, a.grade 
		) t
where
	t.is_passed = true
group by
	t.grade
```

**Comment by charanpreet-s** [comment]
@tushar5526 to do cleanup of query

**Comment by tushar5526** [comment]
Query currently being used. Students are getting grouped properly per class. The only fault is in the logic where only one assessment is being considered for `is_passed` instead of all assessments.
